package audio

import (
	"encoding/json"
	"math"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestHannWindow verifies the periodic Hann window matches torch.hann_window.
// Reference: sum of squared Hann window of length N equals N/2.
func TestHannWindow(t *testing.T) {
	for _, n := range []int{32, 320, 512} {
		w := hannWindow(n)
		assert.Equal(t, n, len(w))
		assert.InDelta(t, 0.0, w[0], 1e-10, "w[0] should be 0")

		var sumsq float64
		for _, v := range w {
			sumsq += v * v
		}
		// Periodic Hann: sum of squares ≈ n/2 * (3/8 * 2) ... actually the
		// exact value is (n * 3) / 8 for the symmetric window; periodic Hann
		// sum-of-squares converges to n*3/8 as n grows.
		// Simpler check: all values in [0, 1].
		for i, v := range w {
			assert.True(t, v >= 0 && v <= 1.0+1e-12, "w[%d]=%v out of range", i, v)
		}
	}
}

// TestFFT verifies the FFT on a known signal.
// A complex exponential e^{j*2π*k*n/N} should produce a spike at bin k.
func TestFFT(t *testing.T) {
	n := 64
	k := 5 // target frequency bin
	x := make([]complex128, n)
	for i := range x {
		angle := 2 * math.Pi * float64(k) * float64(i) / float64(n)
		x[i] = complex(math.Cos(angle), math.Sin(angle))
	}
	fft(x)

	// Bin k should have magnitude ≈ n, all others ≈ 0.
	for i, v := range x {
		mag := math.Sqrt(real(v)*real(v) + imag(v)*imag(v))
		if i == k {
			assert.InDelta(t, float64(n), mag, 1e-8, "expected spike at bin %d", k)
		} else {
			assert.InDelta(t, 0.0, mag, 1e-8, "expected zero at bin %d (got %v)", i, mag)
		}
	}
}

// TestMelFilterbankShape verifies dimensions and non-negativity.
func TestMelFilterbankShape(t *testing.T) {
	for _, norm := range []string{"", "slaney"} {
		fb, err := buildMelFilterbank(80, 512, 16000, 0, 8000, norm)
		require.NoError(t, err)
		assert.Equal(t, 80, len(fb))
		nFreqs := 512/2 + 1
		for b, row := range fb {
			assert.Equal(t, nFreqs, len(row), "bin %d", b)
			for f, w := range row {
				assert.True(t, w >= 0, "negative weight at bin %d freq %d norm=%s", b, f, norm)
			}
		}
	}
}

// TestMelFilterbankHTKCenters spot-checks a few filterbank center frequencies
// against the HTK formula for a 16 kHz, 80-bin filterbank.
func TestMelFilterbankHTKCenters(t *testing.T) {
	fb, err := buildMelFilterbank(80, 512, 16000, 0, 8000, "")
	require.NoError(t, err)

	// Each filter should peak at exactly one FFT bin.
	for b, row := range fb {
		peak := 0.0
		for _, w := range row {
			if w > peak {
				peak = w
			}
		}
		assert.True(t, peak > 0, "filter %d has no energy", b)
	}
}

// TestPreprocessorLogMelShape checks that LogMel returns the expected shape.
func TestPreprocessorLogMelShape(t *testing.T) {
	cfg := DefaultConfig()
	p, err := New(cfg)
	require.NoError(t, err)

	// 1 second of silence at 16 kHz.
	pcm := make([]float32, 16000)
	out, nFrames, err := p.LogMel(pcm)
	require.NoError(t, err)
	assert.Equal(t, cfg.NMelBins*nFrames, len(out))
	// center=True: pad 256 on each side → effective length = 16512.
	// frames = 1 + (16512 - nfft) / hop = 1 + (16512-512)/160 = 101.
	assert.Equal(t, 101, nFrames)
}

// TestPreprocessorNFrames checks that NFrames is consistent with LogMel.
func TestPreprocessorNFrames(t *testing.T) {
	p, err := New(DefaultConfig())
	require.NoError(t, err)

	for _, n := range []int{16000, 32000, 8000, 4800} {
		pcm := make([]float32, n)
		_, nFrames, err := p.LogMel(pcm)
		require.NoError(t, err)
		assert.Equal(t, p.NFrames(n), nFrames, "NFrames mismatch for nSamples=%d", n)
	}
}

// TestLogMelReferenceHTK validates our output against pre-computed values from
// Python/librosa. The reference file is generated by scripts/gen_ref_mel.py.
//
// To regenerate: python3 scripts/gen_ref_mel.py > audio/testdata/ref_mel_htk.json
func TestLogMelReferenceHTK(t *testing.T) {
	refPath := "testdata/ref_mel_htk.json"
	data, err := os.ReadFile(refPath)
	if os.IsNotExist(err) {
		t.Skipf("reference file %s not found — run scripts/gen_ref_mel.py to generate it", refPath)
	}
	require.NoError(t, err)

	var ref struct {
		PCM     []float32 `json:"pcm"`
		LogMel  []float32 `json:"log_mel"` // row-major [nMelBins × nFrames]
		NFrames int       `json:"n_frames"`
		Config  struct {
			SampleRate    int     `json:"sample_rate"`
			WindowSizeSec float64 `json:"window_size"`
			WindowStride  float64 `json:"window_stride"`
			NFft          int     `json:"n_fft"`
			NMelBins      int     `json:"n_mels"`
			FMax          float64 `json:"fmax"`
			Preemph       float64 `json:"preemph"`
		} `json:"config"`
	}
	require.NoError(t, json.Unmarshal(data, &ref))

	cfg := Config{
		SampleRate:    ref.Config.SampleRate,
		WindowSizeSec: ref.Config.WindowSizeSec,
		WindowStride:  ref.Config.WindowStride,
		NFft:          ref.Config.NFft,
		NMelBins:      ref.Config.NMelBins,
		FMax:          ref.Config.FMax,
		MelNorm:       "slaney", // NeMo default
		LogOffset:     1e-6,
		NormType:      NormNone, // compare raw log-mel before normalization
		Preemph:       ref.Config.Preemph,
		Center:        true, // NeMo default
	}
	p, err := New(cfg)
	require.NoError(t, err)

	got, nFrames, err := p.LogMel(ref.PCM)
	require.NoError(t, err)
	assert.Equal(t, ref.NFrames, nFrames)
	require.Equal(t, len(ref.LogMel), len(got))

	// Allow up to 1e-4 absolute difference (float32 precision + small numeric diffs).
	maxDiff := 0.0
	for i := range got {
		d := math.Abs(float64(got[i]) - float64(ref.LogMel[i]))
		if d > maxDiff {
			maxDiff = d
		}
	}
	assert.Less(t, maxDiff, 1e-3, "max absolute difference %v exceeds threshold", maxDiff)
}
